#!/bin/bash
# -----------------------------------------------------------------------------
# buildAnt -- Build Nightly Distribution Files for ANT
#
# Goals:
# - Create nightly distribution files of Ant, including the JAXP reference
#   implementation JAR files (so no extra downloads are needed), in the usual
#   formats
# - Optionally, install these distribution files on the Jakarta web server
#
# Prerequisites:
# - The user under which this script runs must have done a CVS "login"
#   for anonymous access to the Jakarta repositories
# - Java Development Kit, version 1.2.2, installed and configured
#   (avoids compiler problems in 1.1 and 1.3 related to XML classes)
# - Ant 3.1 binary distribution installed
# - ANT_HOME points at this distribution directory (you can set it
#   in ~/.antrc)
# - The "ant" script in $ANT_HOME/bin is accessible on your PATH
# - Java API for XML Parsing (JAXP) 1.0 reference implementation installed
# - JAXP_HOME points at this distribution directory (you can set it
#   in ~/.antrc)
# - The "buildAnt.xml" script (from the Ant source repository) is
#   in the same directory that this script is.
# - To execute the "install" target, you must be running on the Jakarta
#   server, as part of group "jakarta".
#
# Author:	Craig R. McClanahan
# Version:	$Revision$ $Date$
# -----------------------------------------------------------------------------

. ~/.antrc
ant -buildfile buildAnt.xml -Djaxp.home=$JAXP_HOME "$@"
