<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://localhost:8080/axis/StockQuoteService.jws" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:impl="http://localhost:8080/axis/StockQuoteService.jws-impl" xmlns:intf="http://localhost:8080/axis/StockQuoteService.jws" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:message name="getQuoteResponse">
    <wsdl:part name="return" type="xsd:float"/>
  </wsdl:message>
  <wsdl:message name="getQuoteRequest">
    <wsdl:part name="symbol" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="Exception">
  </wsdl:message>
  <wsdl:portType name="StockQuoteService">
    <wsdl:operation name="getQuote" parameterOrder="symbol">
      <wsdl:input message="intf:getQuoteRequest"/>
      <wsdl:output message="intf:getQuoteResponse"/>
      <wsdl:fault message="intf:Exception" name="Exception"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="StockQuoteServiceSoapBinding" type="intf:StockQuoteService">
    <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getQuote">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input>
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost:8080/axis/StockQuoteService.jws" use="encoded"/>
      </wsdl:input>
      <wsdl:output>
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost:8080/axis/StockQuoteService.jws" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="StockQuoteServiceService">
    <wsdl:port binding="intf:StockQuoteServiceSoapBinding" name="StockQuoteService">
      <wsdlsoap:address location="http://localhost:8080/axis/StockQuoteService.jws"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>