<?xml version="1.0" encoding="UTF-8"?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<definitions name="HelloWorld"
targetNamespace="http://hello.jaxrpc.samples/"
xmlns:tns="http://hello.jaxrpc.samples/"
xmlns="http://schemas.xmlsoap.org/wsdl/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types />

  <message name="sayHello">
    <part name="String_1" type="xsd:string" />
  </message>

  <message name="sayHelloResponse">
    <part name="result" type="xsd:string" />
  </message>

  <portType name="Hello">
    <operation name="sayHello" parameterOrder="String_1">
      <input message="tns:sayHello" />

      <output message="tns:sayHelloResponse" />
    </operation>
  </portType>

  <binding name="HelloBinding" type="tns:Hello">
    <operation name="sayHello">
      <input>
        <soap:body
        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
        use="encoded" namespace="http://hello.jaxrpc.samples/" />
      </input>

      <output>
        <soap:body
        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
        use="encoded" namespace="http://hello.jaxrpc.samples/" />
      </output>

      <soap:operation soapAction="" />
    </operation>

    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"
    style="rpc" />
  </binding>

  <service name="HelloWorld">
    <port name="HelloPort" binding="tns:HelloBinding">
      <soap:address
      location="http://localhost:8080/axis/Hello" />
    </port>
  </service>
</definitions>

