/*
 * Copyright (C) The Apache Software Foundation. All rights reserved.
 *
 * This software is published under the terms of the Apache Software License
 * version 1.1, a copy of which has been included with this distribution in
 * the LICENSE.txt file.
 */
package org.apache.tools.ant.taskdefs.optional.junit;

/**
 * <p>
 *
 * Interface groups XML constants. Interface that groups all constants used
 * throughout the <tt>XML</tt> documents that are generated by the <tt>
 * XMLJUnitResultFormatter</tt> As of now the DTD is: <code><pre>
 * <-----------------
 *
 * @author <a href="mailto:sbailliez@imediation.com">Stephane Bailliez</a>
 * @see XMLJUnitResultFormatter
 * @see XMLResultAggregator
 * @todo describe DTDs ----------------------> </pre></code>
 */
public interface XMLConstants
{
    /**
     * the testsuites element for the aggregate document
     */
    String TESTSUITES = "testsuites";

    /**
     * the testsuite element
     */
    String TESTSUITE = "testsuite";

    /**
     * the testcase element
     */
    String TESTCASE = "testcase";

    /**
     * the error element
     */
    String ERROR = "error";

    /**
     * the failure element
     */
    String FAILURE = "failure";

    /**
     * the system-err element
     */
    String SYSTEM_ERR = "system-err";

    /**
     * the system-out element
     */
    String SYSTEM_OUT = "system-out";

    /**
     * package attribute for the aggregate document
     */
    String ATTR_PACKAGE = "package";

    /**
     * name attribute for property, testcase and testsuite elements
     */
    String ATTR_NAME = "name";

    /**
     * time attribute for testcase and testsuite elements
     */
    String ATTR_TIME = "time";

    /**
     * errors attribute for testsuite elements
     */
    String ATTR_ERRORS = "errors";

    /**
     * failures attribute for testsuite elements
     */
    String ATTR_FAILURES = "failures";

    /**
     * tests attribute for testsuite elements
     */
    String ATTR_TESTS = "tests";

    /**
     * type attribute for failure and error elements
     */
    String ATTR_TYPE = "type";

    /**
     * message attribute for failure elements
     */
    String ATTR_MESSAGE = "message";

    /**
     * the properties element
     */
    String PROPERTIES = "properties";

    /**
     * the property element
     */
    String PROPERTY = "property";

    /**
     * value attribute for property elements
     */
    String ATTR_VALUE = "value";

}
